In [1]:
import sys
print(sys.executable)
import hiperwalk, hiperblas
print("Importações OK!")


/opt/intel/oneapi/intelpython/python3.12/bin/python3
Importações OK!


## Coined quantum walk on the two-dimensional grid

In [2]:
#!echo $USER
#!date
#!pwd
#!cd ../../../../hiperblas-core;make clean; make install; ls -ltr
#!cd ../../../../pyhiperblas; pwd;  pip install --user .
#!cd ../../../../hiperwalk; pwd;  pip install --user hiperwalk



In [3]:
import hiperblas
print(hiperblas.__file__)

/prj/prjedlg/bidu/.local/lib/python3.12/site-packages/hiperblas.cpython-312-x86_64-linux-gnu.so


In [4]:
!pip show hiperwalk
import hiperwalk as hpw
import numpy as np

Name: hiperwalk
Version: 2.0b0
Summary: High-Performance Quantum Walk Simulator
Home-page: http://qubit.lncc.br/qwalk/
Author: 
Author-email: Gustavo Bezerra <gbezerra@posgrad.lncc.br>, Paulo Motta <prmottajr@gmail.com>, Renato Portugal <portugal@lncc.br>
License: GNU Lesser General Public License

_Version 3, 29 June 2007_  
_Copyright © 2007 Free Software Foundation, Inc. &lt;<http://fsf.org/>&gt;_

Everyone is permitted to copy and distribute verbatim copies
of this license document, but changing it is not allowed.


This version of the GNU Lesser General Public License incorporates
the terms and conditions of version 3 of the GNU General Public
License, supplemented by the additional permissions listed below.

### 0. Additional Definitions

As used herein, “this License” refers to version 3 of the GNU Lesser
General Public License, and the “GNU GPL” refers to version 3 of the GNU
General Public License.

“The Library” refers to a covered work governed by this License,
other than an

In [5]:
import hiperwalk
print(hiperwalk.__file__)


/prj/prjedlg/bidu/OneDrive/aLncc/passeiosQuantOut25A/hiperwalk/hiperwalk/__init__.py


### Defining the graph and the QW instance

Let set $n$ for the two-dimensional square grid graph with $n^2$ vertices.

In [6]:
n = 5

The next command creates a grid, which is an instance of the Graph class.

In [7]:
grid = hpw.Grid(n, diagonal=True, periodic=False)

The next command creates a QW on the grid, which is an instance of the Coined class.

In [8]:
qw = hpw.Coined(grid, shift='persistent', coin='grover')

em coined.py, __init__
em hiperwalk/quantum_walk/coined.py: def _set_evolution
em _set_evolution, CALL C = self.get_coin(), monta a matriz CSR 
self =  <hiperwalk.quantum_walk.coined.Coined object at 0x7d5e1d93bd70>
++++++  em hiperwalk/quantum_walk/coined.py: get_coin(self)
em get_coin: self._coin= ['grover', 'grover', 'grover', 'grover', 'grover']
em get_coin: scipy.sparse.issparse(self._coin) = False
em get_coin(self), semi-final 
(coin_list)= ['grover', 'grover', 'grover', 'grover', 'grover']
em get_coin(self), final 
em coyned.py, def _set_evolution, U = 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
BD, em hiperwalk/quantum_walk/coined.py, FINAL  def __init__(self, graph=None, **kwargs):


### Setting the initial state with maximum spreading

The central vertex is $(\lfloor n/2\rfloor, \lfloor n/2\rfloor)$. In the next commad, we use np.array to add entrywise in the next command.

In [9]:
center = np.array((n // 2, n // 2))

Note that the computational basis is comprised of arcs, whose labels are $(v_1,v_2)$, where $v_1$, $v_2$ are vertices. Grid vertices have the form $(x,y)$ which represents the coordinate on the grid. Then, the label of an arc is $((x_1,y_1),(x_2,y_2))$.

In [10]:
psi0 = qw.state([(0.5, (center, center + (1, 1))),
                   (-0.5, (center, center + (1, -1))),
                   (-0.5, (center, center + (-1, 1))),
                   (0.5, (center, center + (-1, -1)))])

em coined.py: def state
em coined.py: def state, return


The initial state above represents a walker on the central vertex with the coin in superposition, which is not uniform because some amplitudes are negative in order to achieve maximum spreading.

### Probability distribution

In [ ]:
psi_final = qw.simulate(range=(n//2,n//2+1), state=psi0)
prob = qw.probability_distribution(psi_final)
#hpw.plot_probability_distribution(prob, graph=grid, figsize=(9,4.5))

### Animating the quantum walk

In [1]:
list_of_states = qw.simulate(range = (10,n//2), state = psi0)
list_of_probs = qw.probability_distribution(list_of_states)
#hpw.plot_probability_distribution(list_of_probs, graph=grid, animate=True, figsize=(9,4.5))

NameError: name 'qw' is not defined